// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for Home documents */
interface HomeDocumentData {
    /**
     * Slice Zone field in *Home*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: home.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<HomeDocumentDataSlicesSlice>;
}
/**
 * Slice for *Home → Slice Zone*
 *
 */
type HomeDocumentDataSlicesSlice = HeaderSlice | TestSlice | FeatureGridSlice | FooterSlice;
/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<HomeDocumentData>, "home", Lang>;
export type AllDocumentTypes = HomeDocument;
/**
 * Primary content in FeatureGrid → Primary
 *
 */
interface FeatureGridSliceDefaultPrimary {
    /**
     * FeatureTitle field in *FeatureGrid → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: feature_grid.primary.featuretitle
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    featuretitle: prismicT.KeyTextField;
    /**
     * FeaturePrice field in *FeatureGrid → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: feature_grid.primary.featureprice
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    featureprice: prismicT.KeyTextField;
    /**
     * FeatureTwoTitle field in *FeatureGrid → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: feature_grid.primary.featuretwotitle
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    featuretwotitle: prismicT.KeyTextField;
    /**
     * FeatureTwoPrice field in *FeatureGrid → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: feature_grid.primary.featuretwoprice
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    featuretwoprice: prismicT.KeyTextField;
    /**
     * FeatureThreeTitle field in *FeatureGrid → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: feature_grid.primary.featurethreetitle
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    featurethreetitle: prismicT.KeyTextField;
    /**
     * FeatureThreePrice field in *FeatureGrid → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: feature_grid.primary.featurethreeprice
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    featurethreeprice: prismicT.KeyTextField;
}
/**
 * Item in FeatureGrid → Items
 *
 */
export interface FeatureGridSliceDefaultItem {
    /**
     * FeatureItem field in *FeatureGrid → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: feature_grid.items[].featureitem
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    featureitem: prismicT.KeyTextField;
    /**
     * FeatureTwoItem field in *FeatureGrid → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: feature_grid.items[].featuretwoitem
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    featuretwoitem: prismicT.KeyTextField;
    /**
     * FeatureThreeItem field in *FeatureGrid → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: feature_grid.items[].featurethreeitem
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    featurethreeitem: prismicT.KeyTextField;
}
/**
 * Default variation for FeatureGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: `FeatureGrid`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type FeatureGridSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<FeatureGridSliceDefaultPrimary>, Simplify<FeatureGridSliceDefaultItem>>;
/**
 * Slice variation for *FeatureGrid*
 *
 */
type FeatureGridSliceVariation = FeatureGridSliceDefault;
/**
 * FeatureGrid Shared Slice
 *
 * - **API ID**: `feature_grid`
 * - **Description**: `FeatureGrid`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type FeatureGridSlice = prismicT.SharedSlice<"feature_grid", FeatureGridSliceVariation>;
/**
 * Primary content in Footer → Primary
 *
 */
interface FooterSliceDefaultPrimary {
    /**
     * Copyright field in *Footer → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.primary.copyright
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    copyright: prismicT.KeyTextField;
}
/**
 * Default variation for Footer Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Footer`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type FooterSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<FooterSliceDefaultPrimary>, never>;
/**
 * Slice variation for *Footer*
 *
 */
type FooterSliceVariation = FooterSliceDefault;
/**
 * Footer Shared Slice
 *
 * - **API ID**: `footer`
 * - **Description**: `Footer`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type FooterSlice = prismicT.SharedSlice<"footer", FooterSliceVariation>;
/**
 * Primary content in Header → Primary
 *
 */
interface HeaderSliceDefaultPrimary {
    /**
     * Title field in *Header → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: header.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Logo field in *Header → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: header.primary.logo
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    logo: prismicT.ImageField<never>;
}
/**
 * Item in Header → Items
 *
 */
export interface HeaderSliceDefaultItem {
    /**
     * NavLinks field in *Header → Items*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: header.items[].navlinks
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    navlinks: prismicT.LinkField;
    /**
     * NavTitle field in *Header → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: header.items[].navtitle
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    navtitle: prismicT.KeyTextField;
}
/**
 * Default variation for Header Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Header`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeaderSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<HeaderSliceDefaultPrimary>, Simplify<HeaderSliceDefaultItem>>;
/**
 * Slice variation for *Header*
 *
 */
type HeaderSliceVariation = HeaderSliceDefault;
/**
 * Header Shared Slice
 *
 * - **API ID**: `header`
 * - **Description**: `Header`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeaderSlice = prismicT.SharedSlice<"header", HeaderSliceVariation>;
/**
 * Primary content in Hero → Primary
 *
 */
interface TestSliceDefaultPrimary {
    /**
     * heroImage field in *Hero → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: test.primary.heroimage
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    heroimage: prismicT.ImageField<never>;
    /**
     * heroHeading field in *Hero → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: test.primary.heroheading
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    heroheading: prismicT.KeyTextField;
    /**
     * heroRichText field in *Hero → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: test.primary.herorichtext
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    herorichtext: prismicT.RichTextField;
    /**
     * heroButtonText field in *Hero → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: test.primary.herobuttontext
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    herobuttontext: prismicT.KeyTextField;
}
/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Test`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TestSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<TestSliceDefaultPrimary>, never>;
/**
 * Slice variation for *Hero*
 *
 */
type TestSliceVariation = TestSliceDefault;
/**
 * Hero Shared Slice
 *
 * - **API ID**: `test`
 * - **Description**: `Test`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TestSlice = prismicT.SharedSlice<"test", TestSliceVariation>;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { HomeDocumentData, HomeDocumentDataSlicesSlice, HomeDocument, AllDocumentTypes, FeatureGridSliceDefaultPrimary, FeatureGridSliceDefaultItem, FeatureGridSliceDefault, FeatureGridSliceVariation, FeatureGridSlice, FooterSliceDefaultPrimary, FooterSliceDefault, FooterSliceVariation, FooterSlice, HeaderSliceDefaultPrimary, HeaderSliceDefaultItem, HeaderSliceDefault, HeaderSliceVariation, HeaderSlice, TestSliceDefaultPrimary, TestSliceDefault, TestSliceVariation, TestSlice };
    }
}
