// Code generated by Slice Machine. DO NOT EDIT.

import FeatureGrid from './FeatureGrid';
import Footer from './Footer';
import Header from './Header';
import Hero from './Hero';

export {
	FeatureGrid,
	Footer,
	Header,
	Hero,
};

export const components = {
	feature_grid: FeatureGrid,
	footer: Footer,
	header: Header,
	test: Hero,
};
