// Code generated by Slice Machine. DO NOT EDIT.

import Footer from './Footer';
import Header from './Header';
import Hero from './Hero';
import PlanGrid from './PlanGrid';

export {
	Footer,
	Header,
	Hero,
	PlanGrid,
};

export const components = {
	footer: Footer,
	header: Header,
	test: Hero,
	feature_grid: PlanGrid,
};
