// Code generated by Slice Machine. DO NOT EDIT.

import Hero from './Hero';
import Navigation from './Navigation';
import PlanGrid from './PlanGrid';
import Removed from './Removed';

export {
	Hero,
	Navigation,
	PlanGrid,
	Removed,
};

export const components = {
	test: Hero,
	header: Navigation,
	feature_grid: PlanGrid,
	footer: Removed,
};
